Repository agh-cs-imbeciles/heralds-of-war, pull requests merged in 2025-04, with the labels that each got.

#2 Chore: Ignore .import files in docs/
  .gitignore
Labels: chore

#3 Docs: Add annotation about isometric view
  docs/concept.pdf
  docs/src/concept.tex
Labels: documentation

#4 Feat: Create initial battle map
  assets/sprites/terrain/tileset.png
  assets/sprites/terrain/tileset.png.import
  project.godot
  scenes/game.tscn
Labels: enhancement

#5 Fix: Remove empty Sprite2D node
  scenes/game.tscn
Labels: bug

#7 Feat: Create board highlighting on cursor move
  assets/sprites/terrain/tileset.aseprite
  assets/sprites/terrain/tileset.png
  project.godot
  scenes/game.tscn
  src/terrain/terrain.gd
  src/terrain/terrain.gd.uid
Labels: enhancement

#8 Feat: Add swordsman
  assets/sprites/units/hooded-knight-idle.png
  assets/sprites/units/hooded-knight-idle.png.import
  scenes/game.tscn
  scenes/units/swordsman.tscn
Labels: enhancement, units

#9 Feat: Add basic unit movement
  scenes/game.tscn
  scenes/units/swordsman.tscn
  src/terrain/terrain.gd
  src/units/unit.gd
  src/units/unit.gd.uid
Labels: enhancement, board

#10 Refactor: Rename board highlight tiles
  scenes/game.tscn
  src/terrain/terrain.gd
Labels: refactoring

#11 Refactor: Rename board related components
  scenes/game.tscn
  src/board/board.gd
  src/board/board.gd.uid
Labels: refactoring

#12 Refactor: Replace static highlight tiles with dynamically loaded ones
  scenes/board/highlight-tile.tscn
  scenes/game.tscn
  src/board/board.gd
  src/units/unit.gd
Labels: board, refactoring

#13 Refactor: Set start of the board to point (0, 0)
  scenes/game.tscn
Labels: board, refactoring

#14 Refactor: Replace static swordsman with dynamically loaded one
  scenes/game.tscn
  src/board/board.gd
Labels: board, refactoring

#16 Refactor: Use map position instead of world position in 'Unit'
  src/board/board.gd
  src/units/unit.gd
Labels: units, refactoring

#15 Feat: Limit unit movement range by stamina
  scenes/units/swordsman.tscn
  src/board/board.gd
  src/units/unit.gd
Labels: enhancement, board

#17 Fix: Hide focus and hover tiles on instantiating
  src/board/board.gd
Labels: bug, board

#19 Feat: Add main menu
  assets/fonts/ThaleahFat.ttf
  assets/fonts/ThaleahFat.ttf.import
  project.godot
  scenes/ui/menu/menu.tscn
  src/ui/menu/buttons.gd
  src/ui/menu/buttons.gd.uid
  src/ui/menu/v_box_container.gd
  src/ui/menu/v_box_container.gd.uid
  themes/main_theme.tres
Labels: enhancement, user interface

#21 Chore: Remove redundant 'empty' files
  assets/fonts/empty
  assets/sprites/empty
  scenes/empty
  src/empty
Labels: chore
